# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fe8517d4e958f4e458bd2834080eed6d"
name = "fastChange"
handle = "fastchange"
application_url = "https://pocket-our-scientific-murray.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_locations,write_inventory"

[auth]
redirect_urls = ["https://pocket-our-scientific-murray.trycloudflare.com/auth/callback", "https://pocket-our-scientific-murray.trycloudflare.com/auth/shopify/callback", "https://pocket-our-scientific-murray.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
